name: 'Update Version'
on:
  push:
    branches:
      - '_update-deps/runtimeverification/kontrol'
      - '_update-deps/runtimeverification/rv-nix-tools'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-deps:
    name: 'Update Dependecies'
    runs-on: [self-hosted, linux, flyweight]
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.JENKINS_GITHUB_PAT }}
      - name: 'Configure GitHub user'
        run: |
          git config user.name devops
          git config user.email devops@runtimeverification.com
      - name: 'Install Nix'
        uses: cachix/install-nix-action@v31.2.0
        with:
          install_url: https://releases.nixos.org/nix/nix-2.24.12/install
          extra_nix_config: |
            substituters = http://cache.nixos.org https://cache.iog.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: k-framework
          authToken: ${{ secrets.CACHIX_PUBLIC_TOKEN }}
      - name: 'Install Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: 'Install Poetry'
        uses: Gr1N/setup-poetry@v9
      - name: 'Update Poetry files'
        run: |
          KONTROL_VERSION="$(cat deps/kontrol_release)"
          sed -i 's!kontrol = { git = "https://github.com/runtimeverification/kontrol", tag = "[v0-9\.]*" }!kontrol = { git = "https://github.com/runtimeverification/kontrol", tag = "v'${KONTROL_VERSION}'" }!' pyproject.toml
          poetry update
          git add . && git commit -m "Sync Poetry files: kontrol ${KONTROL_VERSION}" || true
      - name: 'Update K release'
        run: |
          K_VERSION=$(poetry run python3 -c 'import pyk; print(pyk.__version__)')
          echo ${K_VERSION} > deps/k_release
          git add deps/k_release && git commit -m "Sync release file: K ${K_VERSION}" || true
      - name: 'Update Nix flake inputs'
        run: |
          KONTROL_VERSION=$(cat deps/kontrol_release)
          RV_NIX_TOOLS_VERSION=$(cat deps/rv-nix-tools)
          sed -i 's!    kontrol.url = "github:runtimeverification/kontrol/[v0-9\.]*"!    kontrol.url = "github:runtimeverification/kontrol/v'"${KONTROL_VERSION}"'"!' flake.nix
          sed -i 's!    rv-nix-tools.url = "github:runtimeverification/rv-nix-tools/[a-z0-9\.]*"!    rv-nix-tools.url = "github:runtimeverification/rv-nix-tools/'"${RV_NIX_TOOLS_VERSION}"'"!' flake.nix
          nix flake update
          git add flake.nix flake.lock && git commit -m 'flake.{nix,lock}: update Nix derivations' || true
      - name: 'Push updates'
        run: git push
